# Generated by Django 3.2.25 on 2025-07-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_auto_20250714_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
