# Generated by Django 3.2.25 on 2025-07-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0010_studentprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='image',
            new_name='profile_image',
        ),
    ]
