# Generated by Django 3.2.25 on 2025-07-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(default='CSE', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='college',
            field=models.CharField(default='Unknown College', max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year',
            field=models.CharField(default='1st Year', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
