# Generated by Django 3.2.25 on 2025-07-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_auto_20250714_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
