# Generated by Django 3.2.25 on 2025-07-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0008_adminprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrolled_on',
            new_name='enrolled_at',
        ),
    ]
