# Generated by Django 3.2.25 on 2025-07-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0011_rename_image_studentprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
