# Generated by Django 3.2.25 on 2025-09-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0013_contactmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
