# Generated by Django 3.2.25 on 2025-09-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0014_auto_20250913_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='user_type',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
